### ISSUE TITLE
Initialize Organization Management

### ISSUE THREAD

**Issue by r115** [omwami999/PesaLedger#3]
All transactions will be owned by an organization.

This will make it easier to add and manage a team belonging to an organization later on down the road.

For a start, an organization will simply have a name. Other features will be added down the road.

- [ ] Create an `Organization` model.
- [x] Create a migration for the organization. It should have at least two columns. `String: name` and `Int: owner`
- [x] Create api routes for managing the organization

**Comment by omwami999** [comment]
hello ...can we go back and work and work on this project
